# Generated by Django 5.2.3 on 2025-07-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imageuploadcloudinary_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
